### ISSUE TITLE
哪那么多屁事儿? 

### ISSUE THREAD

**Issue by xialeizhou** [formulahendry/1155.Life#1]
955挺好的,   早11 点上班下午5点下班你不如回家养老去吧?
劝你得寸进尺要有个度.

**Comment by zxuqian** [comment]
不是所有人都跟你想法一样好么？就是有大神6个小时能干出12个小时的活来，靠的是业余时间自己提升。当然不上进的除外。

**Comment by nakixii** [comment]
每周工作28小时的国家是不是全体都该回家种地了？
